FROM python:3.9

WORKDIR /app/NeximoChallenge

COPY requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY NeximoChallenge/ .

CMD [ "python","manage.py", "test"]