version: '3'
services:
  solutionapp:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - '8080:8080'
  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile-tests